[colors.primary]
background = "#0C0C0C"
foreground = "#d8d4b4"

[colors.cursor]
text = "#0C0C0C"
cursor = "#9F8A57"

[colors.vi_mode_cursor]
text = "#0C0C0C"
cursor = "#9F8A57"

[colors.search.matches]
foreground = "#0C0C0C"
background = "#525b54"

[colors.search.focused_match]
foreground = "#0C0C0C"
background = "#dd5670"

[colors.footer_bar]
foreground = "#0C0C0C"
background = "#d8d4b4"

[colors.selection]
text = "#0C0C0C"
background = "#d8d4b4"

[colors.normal]
black = "#0C0C0C"
red = "#dd5670"
green = "#2a593f"
yellow = "#525b54"
blue = "#d8d4b4"
magenta = "#689e80"
cyan = "#88c6a3"
white = "#ece4d4"

[colors.bright]
black = "#4e594a"
red = "#dd5670"
green = "#2a593f"
yellow = "#525b54"
blue = "#d8d4b4"
magenta = "#689e80"
cyan = "#88c6a3"
white = "#ece4d4"
