# BACKGROUND
background {
    monitor =
    path = ~/.config/omarchy/current/background
    blur_passes = 0
    contrast = 0.8916
    brightness = 0.8916
    vibrancy = 0.8916
    vibrancy_darkness = 0.0
}

# GENERAL
general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
    ignore_empty_input = true
    hide_cursor = true
}

animations {
    enabled = true
}

# Time
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%I:%M")</span>"
    color = rgba(d8dee9cc)
    font_size = 60
    font_family = JetBrainsMono Nerd Font
    position = 0, 105
    halign = center
    valign = center
}

# Day-Month-Date
label {
    monitor =
    text = cmd[update:1000] echo -e "$(LC_TIME=es_ES.UTF-8 date +"%A, %d de %B")"
    color = rgba(d8dee9cc)
    font_size = 19
    font_family = JetBrainsMono Nerd Font
    position = 0, 45
    halign = center
    valign = center
}

# USER-BOX
shape {
    monitor =
    size = 320, 55
    color = rgba(ffffff1a)
    rounding = -1
    border_size = 0
    border_color = rgba(ffffffff)

    position = 0, -35
    halign = center
    valign = center
}

# USER
label {
    monitor =
    text = cmd[update:86400000] echo "    $(whoami)"
    color = rgba(d8dee9cc)
    font_size = 16
    font_family = JetBrainsMono Nerd Font
    position = 0, -35
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 320, 55
    outline_thickness = 0
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(ffffff00)
    inner_color = rgba(ffffff1a)
    font_color = rgba(c8c8c8ff)
    fade_on_empty = false
    font_family = JetBrainsMono Nerd Font
    placeholder_text = <i><span foreground="##ffffff99">Enter Pass</span></i>
    hide_input = false
    check_color = rgba(89b4faff)
    fail_color = rgba(ff6060ee)
    fail_text = FAIL <b>($ATTEMPTS)</b>
    position = 0, -115
    halign = center
    valign = center
}

auth {
    fingerprint:enabled = false
}
