#!/bin/bash
THEME_NAME=$1

# Cuando se cambia un tema en Omarchy, intenta ejecutar swaybg.
# Como queremos usar hyprpaper para fondos por espacio de trabajo, matamos swaybg.
killall swaybg 2>/dev/null

# Aplicamos los fondos de hyprpaper
~/.config/hypr/scripts/workspace-wallpaper.sh apply >/dev/null 2>&1
