# Extra autostart processes
#exec-once = uwsm-app -- hyprpaper
#exec-once = bash -c "sleep 2 && ~/.config/omarchy/scripts/apply-workspace-wallpapers.sh"
exec-once = bash -c "killall -9 mako 2>/dev/null; exec uwsm-app -- swaync"
exec-once = bash ~/.config/omarchy/scripts/battery-notify.sh

exec-once = bash ~/.config/omarchy/scripts/bg-saver.sh
