# Change the default Omarchy look'n'feel

# https://wiki.hypr.land/Configuring/Basics/Variables/#general
general {
    # No gaps between windows or borders
    # gaps_in = 0
    # gaps_out = 0
    # border_size = 0

    # Change to niri-like side-scrolling layout
    # layout = scrolling
}

# https://wiki.hypr.land/Configuring/Basics/Variables/#decoration
decoration {
    #Use round window corners
    rounding = 8

    # dim_strength = 0.15

    active_opacity = 1
    inactive_opacity = 0.75
}


# https://wiki.hypr.land/Configuring/Basics/Variables/#animations
animations {
    # Disable all animations
    # enabled = no
    animation = fadeLayers, 0, 0, default
}

# https://wiki.hypr.land/Configuring/Basics/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}

# https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/
scrolling {
    # See only one column per screen instead of two
    # column_width = 0.97
}



# SwayNC shadow fixes
layerrule = ignore_alpha 0.1, match:namespace swaync-control-center
layerrule = ignore_alpha 0.1, match:namespace swaync-notification-window

layerrule = animation fadeLayers, match:namespace hyprpaper

env = OMARCHY_THEME_SKIP_BACKGROUND,1

# Fix XWayland scaling issues (like gaps/blurriness) when using fractional scaling (< 1.0)
xwayland {
    force_zero_scaling = true
}
